# ============================================================
#  ملف إعداد بيئة الإنتاج - PostgreSQL
#  التشغيل:  mvn spring-boot:run -Dspring-boot.run.profiles=postgres
# ============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/meetingsdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
