# ============================================================
#  ملف إعداد بيئة الإنتاج - MySQL
#  التشغيل:  mvn spring-boot:run -Dspring-boot.run.profiles=mysql
# ============================================================
spring.datasource.url=jdbc:mysql://localhost:3306/meetingsdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Riyadh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
